### ISSUE TITLE
Problems in the evaluate_RC function

### ISSUE THREAD

**Issue by Brilight** [peaclab/PACT#16]
Hi there, thanks for sharing the PACT project, it is really a good job!

However, when reading the source code, I found a little problem in the GridManager.py:

   you allocate the blocks/units to grids in the evaluate_RC function, and when the block is not aligned to grid, you calculate the allocation ratio with a mask array, right? But let's think a small block just inside a grid, its corresponding mask array will equal to [lb_o] (***mask[-1, 0] = lb_o***), which is not the actual case since the actual ratio is smaller. Furthermore, the following code ***conditions = [mask >= 0.9]*** discards the small area blocks inside each grid, which may even introduce error when the grid size is large.

What's your opinion?

**Comment by yuan1z** [comment]
Hi Brilight,

Thanks for the comment. If the block size is way smaller than a grid, we consider this as architecture level simulation. Architecture simulation with every coarse grid granularity will introduce additional simulation inaccuracy and this is expected. @prachishukla2189 is the developer for evaluate_RC and mesh generation function, she can give you more info on this function.

Thanks

**Comment by Brilight** [comment]
Got it, thanks
